server:
  port: 8082

spring:
  mongodb:
    uri: mongodb+srv://kathikadad12345_db_user:9YTynEm6krg4ECGe@cluster0.ywnumkq.mongodb.net/moviedb-streamphere?appName=Cluster0
jwt:
  secret: mySecretKeymorethan62bit123456