version: '3.8'

services:

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  movie-service:
    build: ./movie-service
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  api-gateway:
    build: ./api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - auth-service
      - movie-service
      - user-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway