spring.application.name=auth-service

# password = m7nUncqlYWQzGRWW
# username = kathikadad12345_db_user
#mongodb+srv://kathikadad12345_db_user:m7nUncqlYWQzGRWW@cluster0.cinal8n.mongodb.net/?appName=Cluster0