server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: movie-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/movies/**

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**